services:
  pdf-extractor:
    build: .
    container_name: pdf-extractor
    restart: unless-stopped

    expose:
      - "8000"

    networks:
      - stackora-network

    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs

networks:
  stackora-network:
    external: true