services:
  app:
    build: .
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - /tmp/pdf_extractor:/tmp

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro   # para SSL con certbot
    depends_on:
      - app
